services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: 
      - pip install -r requirements.txt
      - python manage.py migrate
    startCommand: gunicorn backend.wsgi
